-- 01. TC_CELL_PROCESS

ALTER INDEX IDX_DW_UPDDTM ON dbo.TC_CELL_PROCESS    
DISABLE
--REBUILD WITH (ONLINE=ON, SORT_IN_TEMPDB = ON)    -- 1.5TB
go

/*
    DROP INDEX IDX_DW_UPDDTM ON dbo.TC_CELL_PROCESS
    GO  -- 순식간
*/

-- 02. TC_CELL 도
ALTER INDEX IDX_DW_UPDDTM ON dbo.TC_CELL
DISABLE
--REBUILD WITH (ONLINE=ON, SORT_IN_TEMPDB = ON)    -- 50GB
go

/*
    DROP INDEX IDX_DW_UPDDTM ON dbo.TC_CELL
    GO  -- 순식간
*/