select 'ALTER INDEX ' + name + ' on ' + object_name(object_id) + ' REBUILD' + CHAR(13) + CHAR(10) + 'GO' AS sqls--, object_name(object_id) TName
from SYS.indexes
WHERE object_id = OBJECT_ID('TC_CELL_PROCESS')

SELECT T.name AS TableName, I.name AS IndexName, P.partition_number
    -- , P.partition_id, I.data_space_id, PF.function_id
    , PF.type_desc, R.boundary_id, PF.[type], R.value AS BoundaryValue   
    , P.rows PartitionRows
FROM sys.tables AS T  
    JOIN sys.indexes                        AS I        ON T.object_id = I.object_id  
    JOIN sys.partitions                     AS P        ON I.object_id = P.object_id AND I.index_id = P.index_id   
    JOIN sys.partition_schemes              AS PS       ON I.data_space_id = PS.data_space_id  
    JOIN sys.partition_functions            AS PF       ON PS.function_id = PF.function_id  
    LEFT JOIN sys.partition_range_values    AS R        ON PF.function_id = R.function_id and R.boundary_id = (P.partition_number -1)
WHERE T.name = 'TC_CELL_PROCESS' --AND I.type > 1  
    AND  P.rows > 1
ORDER BY I.index_id, P.partition_number;

-- 01.TC_TRAY
/*
    name	rows	    reserved	    data	        index_size	    unused
    TC_TRAY	4,984,106   12,551,256 KB	3,213,104 KB	6,322,336 KB	3,015,816 KB

    SchemaName  TBL_CreateDate           TableName  IndexType     IndexName         IndexSizeKB  IndexColumn                                                                                                       IncludeColumn                                                                                   STATISTICUPDATEDATE      IS_UNIQUE  IS_UNIQUE_CONSTRAINT  IS_PRIMARY_KEY  HAS_FILTER  FILTER_DEFINITION  IS_DISABLED  database_id  object_id  index_id  user_seeks  user_scans  user_lookups  user_updates  last_user_seek           last_user_scan           last_user_lookup         last_user_update  system_seeks  system_scans  system_lookups  system_updates  last_system_seek  last_system_scan         last_system_lookup  last_system_update  database_id  object_id  index_id  partition_number  leaf_insert_count  leaf_delete_count  leaf_update_count  leaf_ghost_count  nonleaf_insert_count  nonleaf_delete_count  nonleaf_update_count  leaf_allocation_count  nonleaf_allocation_count  leaf_page_merge_count  nonleaf_page_merge_count  range_scan_count  singleton_lookup_count  forwarded_fetch_count  lob_fetch_in_pages  lob_fetch_in_bytes  lob_orphan_create_count  lob_orphan_insert_count  row_overflow_fetch_in_pages  row_overflow_fetch_in_bytes  column_value_push_off_row_count  column_value_pull_in_row_count  row_lock_count  row_lock_wait_count  row_lock_wait_in_ms  page_lock_count  page_lock_wait_count  page_lock_wait_in_ms  index_lock_promotion_attempt_count  index_lock_promotion_count  page_latch_wait_count  page_latch_wait_in_ms  page_io_latch_wait_count  page_io_latch_wait_in_ms  tree_page_latch_wait_count  tree_page_latch_wait_in_ms  tree_page_io_latch_wait_count  tree_page_io_latch_wait_in_ms  page_compression_attempt_count  page_compression_success_count
    ----------  -----------------------  ---------  ------------  ----------------  -----------  ----------------------------------------------------------------------------------------------------------------  ----------------------------------------------------------------------------------------------  -----------------------  ---------  --------------------  --------------  ----------  -----------------  -----------  -----------  ---------  --------  ----------  ----------  ------------  ------------  -----------------------  -----------------------  -----------------------  ----------------  ------------  ------------  --------------  --------------  ----------------  -----------------------  ------------------  ------------------  -----------  ---------  --------  ----------------  -----------------  -----------------  -----------------  ----------------  --------------------  --------------------  --------------------  ---------------------  ------------------------  ---------------------  ------------------------  ----------------  ----------------------  ---------------------  ------------------  ------------------  -----------------------  -----------------------  ---------------------------  ---------------------------  -------------------------------  ------------------------------  --------------  -------------------  -------------------  ---------------  --------------------  --------------------  ----------------------------------  --------------------------  ---------------------  ---------------------  ------------------------  ------------------------  --------------------------  --------------------------  -----------------------------  -----------------------------  ------------------------------  ------------------------------
    dbo         2018-02-28 16:26:01.760  TC_TRAY    CLUSTERED     PK_TC_TRAY        3228056      TRAY_NO ASC                                                                                                       NULL                                                                                            2021-05-31 12:13:17.840  1          0                     1               0           NULL               0            6            871674153  1         134         38          4273891       0             2021-05-31 12:18:20.780  2021-05-27 09:27:53.147  2021-05-27 09:28:17.000  NULL              0             1175          0               0               NULL              2021-05-31 12:13:16.990  NULL                NULL                6            871674153  1         1                 0                  0                  0                  0                 0                     0                     0                     0                      0                         0                      0                         41                648612063252            0                      0                   0                   0                        0                        0                            0                            0                                0                               0               0                    0                    0                0                     0                     0                                   0                           287                    10                     114256                    74675                     58                          1                           7806                           5320                           0                               0
    dbo         2018-02-28 16:26:01.760  TC_TRAY    NONCLUSTERED  FK_TC_TRAY_1       212216      LOT_NO ASC                                                                                                        NULL                                                                                            2021-05-31 12:12:08.043  0          0                     0               0           NULL               0            6            871674153  3         1068684     114645      0             0             2021-05-04 09:34:54.757  2021-04-01 09:00:48.840  NULL                     NULL              0             0             0               0               NULL              NULL                     NULL                NULL                6            871674153  3         1                 0                  0                  0                  0                 0                     0                     0                     0                      0                         0                      0                         2173344           0                       0                      0                   0                   0                        0                        0                            0                            0                                0                               0               0                    0                    0                0                     0                     0                                   0                           0                      0                      4476                      2796                      0                           0                           4476                           2796                           0                               0
    dbo         2018-02-28 16:26:01.760  TC_TRAY    NONCLUSTERED  FK_TC_TRAY_2       282104      PALLET_ID ASC                                                                                                     NULL                                                                                            2021-05-31 12:13:15.277  0          0                     0               0           NULL               0            NULL         NULL       NULL      NULL        NULL        NULL          NULL          NULL                     NULL                     NULL                     NULL              NULL          NULL          NULL            NULL            NULL              NULL                     NULL                NULL                6            871674153  4         1                 0                  0                  0                  0                 0                     0                     0                     0                      0                         0                      0                         0                 0                       0                      0                   0                   0                        0                        0                            0                            0                                0                               0               0                    0                    0                0                     0                     0                                   0                           0                      0                      760                       214                       0                           0                           760                            214                            0                               0
    dbo         2018-02-28 16:26:01.760  TC_TRAY    NONCLUSTERED  FK_TC_TRAY_3       355472      ROUTE_ID ASC, OP_ID ASC                                                                                           NULL                                                                                            2021-05-31 12:13:15.487  0          0                     0               0           NULL               0            6            871674153  5         4158194     114644      0             0             2021-05-07 10:20:37.830  2021-04-01 09:00:48.840  NULL                     NULL              0             0             0               0               NULL              NULL                     NULL                NULL                6            871674153  5         1                 0                  0                  0                  0                 0                     0                     0                     0                      0                         0                      0                         52607283          0                       0                      0                   0                   0                        0                        0                            0                            0                                0                               0               0                    0                    0                0                     0                     0                                   0                           12                     11                     7403                      6519                      12                          11                          7403                           6519                           0                               0
    dbo         2018-02-28 16:26:01.760  TC_TRAY    NONCLUSTERED  FK_TC_TRAY_4       180432      TRAY_TYPE_CD ASC                                                                                                  NULL                                                                                            2021-05-31 12:13:15.720  0          0                     0               0           NULL               0            NULL         NULL       NULL      NULL        NULL        NULL          NULL          NULL                     NULL                     NULL                     NULL              NULL          NULL          NULL            NULL            NULL              NULL                     NULL                NULL                6            871674153  6         1                 0                  0                  0                  0                 0                     0                     0                     0                      0                         0                      0                         0                 0                       0                      0                   0                   0                        0                        0                            0                            0                                0                               0               0                    0                    0                0                     0                     0                                   0                           0                      0                      573                       173                       0                           0                           573                            173                            0                               0
    dbo         2018-02-28 16:26:01.760  TC_TRAY    NONCLUSTERED  FK_TC_TRAY_5       169608      LINE_ID ASC                                                                                                       NULL                                                                                            2021-05-31 12:13:15.887  0          0                     0               0           NULL               0            6            871674153  7         33          0           0             0             2021-05-27 08:40:01.003  NULL                     NULL                     NULL              0             130           0               0               NULL              2021-05-31 12:13:17.740  NULL                NULL                6            871674153  7         1                 0                  0                  0                  0                 0                     0                     0                     0                      0                         0                      0                         36                0                       0                      0                   0                   0                        0                        0                            0                            0                                0                               0               0                    0                    0                0                     0                     0                                   0                           0                      0                      555                       195                       0                           0                           555                            195                            0                               0
    dbo         2018-02-28 16:26:01.760  TC_TRAY    NONCLUSTERED  FK_TC_TRAY_6       389704      ROUTE_ID ASC, JUDG_OP_ID ASC                                                                                      NULL                                                                                            2021-05-31 12:13:16.180  0          0                     0               0           NULL               0            6            871674153  8         308         0           0             0             2021-04-01 09:00:48.840  NULL                     NULL                     NULL              0             108           0               0               NULL              2021-05-04 09:33:12.113  NULL                NULL                6            871674153  8         1                 0                  0                  0                  0                 0                     0                     0                     0                      0                         0                      0                         2829              0                       0                      0                   0                   0                        0                        0                            0                            0                                0                               0               0                    0                    0                0                     0                     0                                   0                           0                      0                      1792                      686                       0                           0                           1792                           686                            0                               0
    dbo         2018-02-28 16:26:01.760  TC_TRAY    NONCLUSTERED  IX_TC_TRAY_FC_I7   435104      FIN_CD ASC                                                                                                        TRAY_NO, LOT_NO, ROUTE_ID, OP_ID, OP_PLAN_TIME, TRAY_OP_STATUS_CD, SPECIAL_YN                   2021-05-31 08:58:54.543  0          0                     0               0           NULL               0            6            871674153  44        45          0           0             0             2021-05-28 09:15:30.567  NULL                     NULL                     NULL              0             58            0               0               NULL              2021-05-31 12:13:15.283  NULL                NULL                6            871674153  44        1                 0                  0                  0                  0                 0                     0                     0                     0                      0                         0                      0                         132               0                       0                      0                   0                   0                        0                        0                            0                            0                                0                               0               0                    0                    0                0                     0                     0                                   0                           0                      0                      280                       193                       0                           0                           280                            193                            0                               0
    dbo         2018-02-28 16:26:01.760  TC_TRAY    NONCLUSTERED  IX_TC_TRAY_N2     1062736      TRAY_ID ASC, FIN_CD ASC                                                                                           TRAY_OP_STATUS_CD, OP_PLAN_TIME, NEXT_OP_LANE_ID, AGING_OUT_PRIORITY, EQP_ID, MDF_TIME, MDF_ID  2021-05-31 12:13:14.813  0          0                     0               0           NULL               0            6            871674153  2         317         0           0             0             2021-04-20 19:05:42.810  NULL                     NULL                     NULL              0             0             0               0               NULL              NULL                     NULL                NULL                6            871674153  2         1                 0                  0                  0                  0                 0                     0                     0                     0                      0                         0                      0                         345039            0                       0                      0                   0                   0                        0                        0                            0                            0                                0                               0               0                    0                    0                0                     0                     0                                   0                           0                      0                      3361                      1023                      0                           0                           3361                           1023                           0                               0
    dbo         2018-02-28 16:26:01.760  TC_TRAY    NONCLUSTERED  IX_TC_TRAY_N3      450408      FIN_CD ASC, TRAY_OP_STATUS_CD ASC, OP_PLAN_TIME ASC                                                               NULL                                                                                            2021-05-31 12:13:16.707  0          0                     0               0           NULL               0            6            871674153  11        119         0           0             0             2021-04-07 11:29:16.527  NULL                     NULL                     NULL              0             9             0               0               NULL              2021-04-05 11:18:50.090  NULL                NULL                6            871674153  11        1                 0                  0                  0                  0                 0                     0                     0                     0                      0                         0                      0                         566               0                       0                      0                   0                   0                        0                        0                            0                            0                                0                               0               0                    0                    0                0                     0                     0                                   0                           0                      0                      3067                      1142                      0                           0                           3067                           1142                           0                               0
    dbo         2018-02-28 16:26:01.760  TC_TRAY    NONCLUSTERED  IX_TC_TRAY_N4      244632      LOT_NO ASC, LINE_ID ASC, TRAY_NO ASC                                                                              NULL                                                                                            2021-05-31 12:13:00.397  0          0                     0               0           NULL               0            6            871674153  12        2           0           0             0             2021-04-26 15:43:15.720  NULL                     NULL                     NULL              0             130           0               0               NULL              2021-05-31 12:13:15.723  NULL                NULL                6            871674153  12        1                 0                  0                  0                  0                 0                     0                     0                     0                      0                         0                      0                         2                 0                       0                      0                   0                   0                        0                        0                            0                            0                                0                               0               0                    0                    0                0                     0                     0                                   0                           0                      0                      746                       229                       0                           0                           746                            229                            0                               0
    dbo         2018-02-28 16:26:01.760  TC_TRAY    NONCLUSTERED  IX_TC_TRAY_N5      570688      FIN_CD ASC, OP_ID ASC, EQP_ID ASC                                                                                 ROUTE_ID, OP_PLAN_TIME                                                                          2021-05-31 12:13:17.737  0          0                     0               0           NULL               0            6            871674153  15        50          0           0             0             2021-04-22 10:52:53.743  NULL                     NULL                     NULL              0             114           0               0               NULL              2021-05-14 11:14:49.277  NULL                NULL                6            871674153  15        1                 0                  0                  0                  0                 0                     0                     0                     0                      0                         0                      0                         337604            0                       0                      0                   0                   0                        0                        0                            0                            0                                0                               0               0                    0                    0                0                     0                     0                                   0                           0                      0                      4218                      12165                     0                           0                           4218                           12165                          0                               0
    dbo         2018-02-28 16:26:01.760  TC_TRAY    NONCLUSTERED  IX_TC_TRAY_N6      697568      FIN_CD ASC, OP_ID ASC, EQP_ID ASC, MDF_TIME ASC                                                                   TRAY_ID, ROUTE_ID, OP_SEQ, OP_PLAN_TIME, TRAY_OP_STATUS_CD, AGING_OUT_PRIORITY                  2021-05-31 12:13:16.430  0          0                     0               0           NULL               0            6            871674153  10        31          0           0             0             2021-05-14 11:26:20.597  NULL                     NULL                     NULL              0             135           0               0               NULL              2021-05-31 12:13:16.710  NULL                NULL                6            871674153  10        1                 0                  0                  0                  0                 0                     0                     0                     0                      0                         0                      0                         28                0                       0                      0                   0                   0                        0                        0                            0                            0                                0                               0               0                    0                    0                0                     0                     0                                   0                           0                      0                      4854                      1560                      0                           0                           4854                           1560                           0                               0
    dbo         2018-02-28 16:26:01.760  TC_TRAY    NONCLUSTERED  IX_TC_TRAY_N7      588008      FIN_CD ASC, NEXT_OP_LANE_ID ASC, MOVE_ON_YN ASC, OP_ID ASC, TRAY_OP_STATUS_CD ASC, MDF_TIME ASC                   TRAY_ID, ROUTE_ID, OP_SEQ, AGING_OUT_PRIORITY                                                   2021-05-31 12:13:17.513  0          0                     0               0           NULL               0            6            871674153  14        13          1           0             0             2021-03-08 14:49:03.633  2021-05-27 09:28:17.000  NULL                     NULL              0             300           0               0               NULL              2021-05-31 12:13:14.510  NULL                NULL                6            871674153  14        1                 0                  0                  0                  0                 0                     0                     0                     0                      0                         0                      0                         18                0                       0                      0                   0                   0                        0                        0                            0                            0                                0                               0               0                    0                    0                0                     0                     0                                   0                           0                      0                      10464                     2525                      0                           0                           10464                          2525                           0                               0
    dbo         2018-02-28 16:26:01.760  TC_TRAY    NONCLUSTERED  IX_TC_TRAY_N8      668656      OP_ID ASC, FIN_CD ASC, TRAY_OP_STATUS_CD ASC, MDF_TIME ASC, EQP_ID ASC, OP_PLAN_TIME ASC, AGING_OUT_PRIORITY ASC  ROUTE_ID, OP_SEQ                                                                                2021-05-31 12:13:16.990  0          0                     0               0           NULL               0            6            871674153  13        19          0           0             0             2021-05-14 11:29:08.570  NULL                     NULL                     NULL              0             406           0               0               NULL              2021-05-31 12:13:17.513  NULL                NULL                6            871674153  13        1                 0                  0                  0                  0                 0                     0                     0                     0                      0                         0                      0                         10706             0                       0                      0                   0                   0                        0                        0                            0                            0                                0                               0               0                    0                    0                0                     0                     0                                   0                           0                      0                      10502                     3453                      0                           0                           10502                          3453                           0                               0
*/    

    ALTER INDEX FK_TC_TRAY_1 on TC_TRAY REBUILD WITH (ONLINE=ON)    -- 00:00:03 이 아래 시간은 모두 같음
    GO
    ALTER INDEX FK_TC_TRAY_2 on TC_TRAY REBUILD WITH (ONLINE=ON)
    GO
    ALTER INDEX FK_TC_TRAY_3 on TC_TRAY REBUILD WITH (ONLINE=ON)
    GO
    ALTER INDEX FK_TC_TRAY_4 on TC_TRAY REBUILD WITH (ONLINE=ON)
    GO
    ALTER INDEX FK_TC_TRAY_5 on TC_TRAY REBUILD WITH (ONLINE=ON)
    GO
    ALTER INDEX FK_TC_TRAY_6 on TC_TRAY REBUILD WITH (ONLINE=ON)
    GO

    ALTER INDEX IX_TC_TRAY_N2 on TC_TRAY REBUILD WITH (ONLINE=ON)   -- 00:00:06
    GO

    ALTER INDEX IX_TC_TRAY_N6 on TC_TRAY REBUILD WITH (ONLINE=ON)
    GO
    ALTER INDEX IX_TC_TRAY_N3 on TC_TRAY REBUILD WITH (ONLINE=ON)   -- 00:00:09
    GO
    ALTER INDEX IX_TC_TRAY_N4 on TC_TRAY REBUILD WITH (ONLINE=ON)
    GO
    ALTER INDEX IX_TC_TRAY_N8 on TC_TRAY REBUILD WITH (ONLINE=ON)
    GO
    ALTER INDEX IX_TC_TRAY_N7 on TC_TRAY REBUILD WITH (ONLINE=ON)   -- 00:00:09
    GO
    ALTER INDEX IX_TC_TRAY_N5 on TC_TRAY REBUILD WITH (ONLINE=ON)
    GO
    ALTER INDEX IX_TC_TRAY_FC_I7 on TC_TRAY REBUILD WITH (ONLINE=ON)   -- 00:00:19
    GO
    ALTER INDEX PK_TC_TRAY on TC_TRAY
    REBUILD
         WITH (ONLINE=ON)      -- 00:00:19
        -- WITH (SORT_IN_TEMPDB = ON) ON [PRIMARY]       -- 01:40
        -- sort_in_tempdb = on 이 비슷하거나 약간 느린게 test db 서버는 깔끔한 상태라서 처음부터 깨져 있지 않기 때문으로 추측.
        -- 실서버에서느 sort_in_tempdb로 해보자
        -- 아니면 cl이라서?
    GO

-- 02.TC_TRAY_PROCESS
/*
    name             rows         reserved        data         index_size   unused
    ---------------  ---------    --------------  -----------  -----------  ------------------
    TC_TRAY_PROCESS  120,189,146  125,172,312 KB  47120568 KB  77976472 KB  75272 KB

    SchemaName  TBL_CreateDate           TableName        IndexType     IndexName              IndexSizeKB    IndexColumn                                IncludeColumn  STATISTICUPDATEDATE      IS_UNIQUE  IS_UNIQUE_CONSTRAINT  IS_PRIMARY_KEY  HAS_FILTER  FILTER_DEFINITION  IS_DISABLED  database_id  object_id  index_id  user_seeks  user_scans  user_lookups  user_updates  last_user_seek           last_user_scan           last_user_lookup  last_user_update  system_seeks  system_scans  system_lookups  system_updates  last_system_seek  last_system_scan         last_system_lookup  last_system_update  database_id  object_id  index_id  partition_number  leaf_insert_count  leaf_delete_count  leaf_update_count  leaf_ghost_count  nonleaf_insert_count  nonleaf_delete_count  nonleaf_update_count  leaf_allocation_count  nonleaf_allocation_count  leaf_page_merge_count  nonleaf_page_merge_count  range_scan_count  singleton_lookup_count  forwarded_fetch_count  lob_fetch_in_pages  lob_fetch_in_bytes  lob_orphan_create_count  lob_orphan_insert_count  row_overflow_fetch_in_pages  row_overflow_fetch_in_bytes  column_value_push_off_row_count  column_value_pull_in_row_count  row_lock_count  row_lock_wait_count  row_lock_wait_in_ms  page_lock_count  page_lock_wait_count  page_lock_wait_in_ms  index_lock_promotion_attempt_count  index_lock_promotion_count  page_latch_wait_count  page_latch_wait_in_ms  page_io_latch_wait_count  page_io_latch_wait_in_ms  tree_page_latch_wait_count  tree_page_latch_wait_in_ms  tree_page_io_latch_wait_count  tree_page_io_latch_wait_in_ms  page_compression_attempt_count  page_compression_success_count
    ----------  -----------------------  ---------------  ------------  ---------------------  -----------    -----------------------------------------  -------------  -----------------------  ---------  --------------------  --------------  ----------  -----------------  -----------  -----------  ---------  --------  ----------  ----------  ------------  ------------  -----------------------  -----------------------  ----------------  ----------------  ------------  ------------  --------------  --------------  ----------------  -----------------------  ------------------  ------------------  -----------  ---------  --------  ----------------  -----------------  -----------------  -----------------  ----------------  --------------------  --------------------  --------------------  ---------------------  ------------------------  ---------------------  ------------------------  ----------------  ----------------------  ---------------------  ------------------  ------------------  -----------------------  -----------------------  ---------------------------  ---------------------------  -------------------------------  ------------------------------  --------------  -------------------  -------------------  ---------------  --------------------  --------------------  ----------------------------------  --------------------------  ---------------------  ---------------------  ------------------------  ------------------------  --------------------------  --------------------------  -----------------------------  -----------------------------  ------------------------------  ------------------------------
    dbo         2018-02-28 16:26:01.790  TC_TRAY_PROCESS  CLUSTERED     PK_TC_TRAY_PROCESS     47,316,624     TRAY_NO ASC, OP_ID ASC                     NULL           2021-05-31 08:59:02.923  1          0                     1               0           NULL               0            6            967674495  1         168         5           0             0             2021-05-08 08:00:08.297  2021-05-25 18:02:42.017  NULL              NULL              0             101           0               0               NULL              2021-05-27 08:37:04.453  NULL                NULL                6            967674495  1         1                 0                  0                  0                  0                 0                     0                     0                     0                      0                         0                      0                         12211             197620                  0                      0                   0                   0                        0                        0                            0                            0                                0                               0               0                    0                    0                0                     0                     0                                   0                           0                      0                      99343                     34087                     0                           0                           93042                          32596                          0                               0
    dbo         2018-02-28 16:26:01.790  TC_TRAY_PROCESS  NONCLUSTERED  FK_TC_TRAY_PROCESS_1   11,401,864     EQP_ID ASC                                 NULL           2021-05-31 08:59:05.100  0          0                     0               0           NULL               0            NULL         NULL       NULL      NULL        NULL        NULL          NULL          NULL                     NULL                     NULL              NULL              NULL          NULL          NULL            NULL            NULL              NULL                     NULL                NULL                6            967674495  2         1                 0                  0                  0                  0                 0                     0                     0                     0                      0                         0                      0                         0                 0                       0                      0                   0                   0                        0                        0                            0                            0                                0                               0               0                    0                    0                0                     0                     0                                   0                           0                      0                      37923                     9819                      0                           0                           37923                          9819                           0                               0
    dbo         2018-02-28 16:26:01.790  TC_TRAY_PROCESS  NONCLUSTERED  FK_TC_TRAY_PROCESS_2    8,643,928     OP_ID ASC, ROUTE_ID ASC                    NULL           2021-05-31 08:59:07.083  0          0                     0               0           NULL               0            6            967674495  3         0           12          0             0             NULL                     2021-05-27 08:38:36.350  NULL              NULL              0             24            0               0               NULL              2021-05-27 08:36:56.663  NULL                NULL                6            967674495  3         1                 0                  0                  0                  0                 0                     0                     0                     0                      0                         0                      0                         9                 0                       0                      0                   0                   0                        0                        0                            0                            0                                0                               0               0                    0                    0                0                     0                     0                                   0                           0                      0                      26814                     8833                      0                           0                           26814                          8833                           0                               0
    dbo         2018-02-28 16:26:01.790  TC_TRAY_PROCESS  NONCLUSTERED  IX_TC_TRAY_PROCESS_N3  13,506,160     OP_START_TIME ASC                          NULL           2021-05-31 08:59:08.240  0          0                     0               0           NULL               0            6            967674495  6         0           0           0             0             NULL                     NULL                     NULL              NULL              0             21            0               0               NULL              2021-05-27 08:37:01.730  NULL                NULL                6            967674495  6         1                 0                  0                  0                  0                 0                     0                     0                     0                      0                         0                      0                         0                 0                       0                      0                   0                   0                        0                        0                            0                            0                                0                               0               0                    0                    0                0                     0                     0                                   0                           0                      0                      42214                     10138                     0                           0                           42214                          10138                          0                               0
    dbo         2018-02-28 16:26:01.790  TC_TRAY_PROCESS  NONCLUSTERED  IX_TC_TRAY_PROCESS_N4  10,430,992     TRAY_NO ASC, OP_ID ASC, OP_START_TIME ASC  NULL           2021-05-31 08:59:09.460  0          0                     0               0           NULL               0            6            967674495  7         84          2           0             0             2021-05-14 11:29:08.570  2021-03-08 14:49:03.633  NULL              NULL              0             21            0               0               NULL              2021-05-27 08:37:00.507  NULL                NULL                6            967674495  7         1                 0                  0                  0                  0                 0                     0                     0                     0                      0                         0                      0                         2272773           0                       0                      0                   0                   0                        0                        0                            0                            0                                0                               0               0                    0                    0                0                     0                     0                                   0                           0                      0                      67316                     25773                     0                           0                           67316                          25773                          0                               0
    dbo         2018-02-28 16:26:01.790  TC_TRAY_PROCESS  NONCLUSTERED  IX_TC_TRAY_PROCESS_N5  14,064,864     OP_END_TIME ASC, OP_ID ASC                 NULL           2021-05-31 08:59:11.307  0          0                     0               0           NULL               0            NULL         NULL       NULL      NULL        NULL        NULL          NULL          NULL                     NULL                     NULL              NULL              NULL          NULL          NULL            NULL            NULL              NULL                     NULL                NULL                6            967674495  8         1                 0                  0                  0                  0                 0                     0                     0                     0                      0                         0                      0                         0                 0                       0                      0                   0                   0                        0                        0                            0                            0                                0                               0               0                    0                    0                0                     0                     0                                   0                           0                      0                      44217                     10399                     0                           0                           44217                          10399                          0                               0
    dbo         2018-02-28 16:26:01.790  TC_TRAY_PROCESS  NONCLUSTERED  IX_TC_TRAY_PROCESS_N6  19,732,656     OP_START_TIME ASC, EQP_ID ASC              IN_CELL_CNT    2021-05-31 08:59:12.920  0          0                     0               0           NULL               0            6            967674495  9         0           0           0             0             NULL                     NULL                     NULL              NULL              0             21            0               0               NULL              2021-05-27 08:36:57.233  NULL                NULL                6            967674495  9         1                 0                  0                  0                  0                 0                     0                     0                     0                      0                         0                      0                         0                 0                       0                      0                   0                   0                        0                        0                            0                            0                                0                               0               0                    0                    0                0                     0                     0                                   0                           0                      0                      87922                     23202                     0                           0                           87922                          23202                          0                               0
*/

    -- 이땍 통계UPDATE가 같이 실행되어 더 느렸음
    ALTER INDEX FK_TC_TRAY_PROCESS_1 on TC_TRAY_PROCESS
    REBUILD WITH (ONLINE=ON)                                -- 00:01:18     CXPACKET WAIT 맣이 발생
    GO
    ALTER INDEX FK_TC_TRAY_PROCESS_2 on TC_TRAY_PROCESS
    --REBUILD  WITH (ONLINE=ON, SORT_IN_TEMPDB=ON)            -- 00:01:19
    REBUILD  WITH (ONLINE=ON)            -- 00:01:16
    --REBUILD WITH (ONLINE=ON, SORT_IN_TEMPDB=ON, MAXDOP=1)            -- 00:03:12
    --REBUILD WITH (ONLINE=ON, SORT_IN_TEMPDB=ON, MAXDOP=8)            -- 00:01:26
    GO
    ALTER INDEX IX_TC_TRAY_PROCESS_N3 on TC_TRAY_PROCESS REBUILD WITH (ONLINE=ON)   -- 00:01:27
    GO
    ALTER INDEX IX_TC_TRAY_PROCESS_N4 on TC_TRAY_PROCESS REBUILD WITH (ONLINE=ON)   -- 00:01:27
    GO
    ALTER INDEX IX_TC_TRAY_PROCESS_N5 on TC_TRAY_PROCESS REBUILD WITH (ONLINE=ON)   -- 00:01:29
    GO
    ALTER INDEX IX_TC_TRAY_PROCESS_N6 on TC_TRAY_PROCESS REBUILD WITH (ONLINE=ON, SORT_IN_TEMPDB=ON)    -- 00:02:15
    GO

    ALTER INDEX PK_TC_TRAY_PROCESS on TC_TRAY_PROCESS REBUILD WITH (ONLINE=ON)      -- 00:06:51
    GO


-- 03. TC_CELL
/*
    name     rows         reserved      data         index_size    unused
    -------  ---------    ------------  -----------  ------------  ------------------
    TC_CELL  493,449,445  212,455,792 KB  75876464 KB  134351824 KB  2227504 KB




    SchemaName  TBL_CreateDate           TableName  IndexType     IndexName      IndexSizeKB  IndexColumn               IncludeColumn  STATISTICUPDATEDATE      IS_UNIQUE  IS_UNIQUE_CONSTRAINT  IS_PRIMARY_KEY  HAS_FILTER  FILTER_DEFINITION  IS_DISABLED  database_id  object_id  index_id  user_seeks  user_scans  user_lookups  user_updates  last_user_seek           last_user_scan           last_user_lookup         last_user_update  system_seeks  system_scans  system_lookups  system_updates  last_system_seek  last_system_scan         last_system_lookup  last_system_update  database_id  object_id  index_id  partition_number  leaf_insert_count  leaf_delete_count  leaf_update_count  leaf_ghost_count  nonleaf_insert_count  nonleaf_delete_count  nonleaf_update_count  leaf_allocation_count  nonleaf_allocation_count  leaf_page_merge_count  nonleaf_page_merge_count  range_scan_count  singleton_lookup_count  forwarded_fetch_count  lob_fetch_in_pages  lob_fetch_in_bytes  lob_orphan_create_count  lob_orphan_insert_count  row_overflow_fetch_in_pages  row_overflow_fetch_in_bytes  column_value_push_off_row_count  column_value_pull_in_row_count  row_lock_count  row_lock_wait_count  row_lock_wait_in_ms  page_lock_count  page_lock_wait_count  page_lock_wait_in_ms  index_lock_promotion_attempt_count  index_lock_promotion_count  page_latch_wait_count  page_latch_wait_in_ms  page_io_latch_wait_count  page_io_latch_wait_in_ms  tree_page_latch_wait_count  tree_page_latch_wait_in_ms  tree_page_io_latch_wait_count  tree_page_io_latch_wait_in_ms  page_compression_attempt_count  page_compression_success_count
    ----------  -----------------------  ---------  ------------  -------------  -----------  ------------------------  -------------  -----------------------  ---------  --------------------  --------------  ----------  -----------------  -----------  -----------  ---------  --------  ----------  ----------  ------------  ------------  -----------------------  -----------------------  -----------------------  ----------------  ------------  ------------  --------------  --------------  ----------------  -----------------------  ------------------  ------------------  -----------  ---------  --------  ----------------  -----------------  -----------------  -----------------  ----------------  --------------------  --------------------  --------------------  ---------------------  ------------------------  ---------------------  ------------------------  ----------------  ----------------------  ---------------------  ------------------  ------------------  -----------------------  -----------------------  ---------------------------  ---------------------------  -------------------------------  ------------------------------  --------------  -------------------  -------------------  ---------------  --------------------  --------------------  ----------------------------------  --------------------------  ---------------------  ---------------------  ------------------------  ------------------------  --------------------------  --------------------------  -----------------------------  -----------------------------  ------------------------------  ------------------------------
    dbo         2018-06-12 15:34:39.153  TC_CELL    CLUSTERED     PK_TC_CELL     76,312,672   TRAY_NO ASC, CELL_NO ASC  NULL           2021-05-31 09:30:20.040  1          0                     1               0           NULL               0            6            341628310  1         554         47          74            0             2021-05-31 12:18:20.780  2021-05-26 14:03:32.910  2021-05-31 12:12:39.773  NULL              0             118           0               0               NULL              2021-05-31 09:30:20.040  NULL                NULL                6            341628310  1         6                 0                  0                  0                  0                 0                     0                     0                     0                      0                         0                      0                         197075            842                     0                      0                   0                   0                        0                        0                            0                            0                                0                               0               0                    0                    0                0                     0                     0                                   0                           0                      0                      250115                    715573                    0                           0                           163876                         589209                         0                               0
    dbo         2018-06-12 15:34:39.153  TC_CELL    NONCLUSTERED  FK_CC_CT_1     16,253,984   TRAY_NO ASC               NULL           2021-05-31 09:30:23.557  0          0                     0               0           NULL               0            6            341628310  4         128         3           0             0             2021-05-28 09:15:30.567  2021-05-27 08:14:03.153  NULL                     NULL              0             15            0               0               NULL              2021-05-31 11:11:39.420  NULL                NULL                6            341628310  4         6                 0                  0                  0                  0                 0                     0                     0                     0                      0                         0                      0                         489839            0                       0                      0                   0                   0                        0                        0                            0                            0                                0                               0               0                    0                    0                0                     0                     0                                   0                           0                      0                      13595                     7540                      0                           0                           13595                          7540                           0                               0
    dbo         2018-06-12 15:34:39.153  TC_CELL    NONCLUSTERED  IDX_DW_UPDDTM  51,369,072   UPDDTTM ASC, TRAY_NO ASC  NULL           2021-05-31 09:30:21.927  0          0                     0               0           NULL               0            6            341628310  3         19          2           0             0             2021-04-27 08:13:12.043  2021-03-19 16:30:40.550  NULL                     NULL              0             96            0               0               NULL              2021-05-31 09:30:21.930  NULL                NULL                6            341628310  3         6                 0                  0                  0                  0                 0                     0                     0                     0                      0                         0                      0                         19                0                       0                      0                   0                   0                        0                        0                            0                            0                                0                               0               0                    0                    0                0                     0                     0                                   0                           0                      0                      86237                     30630                     0                           0                           86237                          30630                          0                               0
    dbo         2018-06-12 15:34:39.153  TC_CELL    NONCLUSTERED  IX_TC_CELL_01  66,292,232   CELL_ID ASC, TRAY_NO ASC  NULL           2021-05-31 09:30:17.373  0          0                     0               0           NULL               0            6            341628310  2         142         9           0             0             2021-05-31 12:12:39.773  2021-03-29 15:15:57.033  NULL                     NULL              0             0             0               0               NULL              NULL                     NULL                NULL                6            341628310  2         6                 0                  0                  0                  0                 0                     0                     0                     0                      0                         0                      0                         33745             0                       0                      0                   0                   0                        0                        0                            0                            0                                0                               0               0                    0                    0                0                     0                     0                                   0                           0                      0                      122435                    48528                     0                           0                           122435                         48528                          0                               0

    TableName	IndexName	    partition_number	type_desc	boundary_id	type	BoundaryValue	PartitionRows
    TC_CELL	    PK_TC_CELL	    6	                RANGE	    5	        R 	    2000001	        53,549,174
    TC_CELL	    PK_TC_CELL	    7	                RANGE	    6	        R 	    2400001	        50,482,596
    TC_CELL	    PK_TC_CELL	    8	                RANGE	    7	        R 	    2800001	        54,368,994
    TC_CELL	    PK_TC_CELL	    9	                RANGE	    8	        R 	    3200001	        55,547,316
    TC_CELL	    PK_TC_CELL	    10	                RANGE	    9	        R 	    3600001	        77,420,538
    TC_CELL	    PK_TC_CELL	    11	                RANGE	    10	        R 	    4000001	        80,402,102
    TC_CELL	    PK_TC_CELL	    12	                RANGE	    11	        R 	    4400001	        81,008,600
    TC_CELL	    PK_TC_CELL	    13	                RANGE	    12	        R 	    4800001	        40,673,245
    TC_CELL	    IX_TC_CELL_01	6	                RANGE	    5	        R 	    2000001	        53,549,174
    TC_CELL	    IX_TC_CELL_01	7	                RANGE	    6	        R 	    2400001	        50,482,596
    TC_CELL	    IX_TC_CELL_01	8	                RANGE	    7	        R 	    2800001	        54,368,994
    TC_CELL	    IX_TC_CELL_01	9	                RANGE	    8	        R 	    3200001	        55,547,316
    TC_CELL	    IX_TC_CELL_01	10	                RANGE	    9	        R 	    3600001	        77,420,538
    TC_CELL	    IX_TC_CELL_01	11	                RANGE	    10	        R 	    4000001	        80,402,102
    TC_CELL	    IX_TC_CELL_01	12	                RANGE	    11	        R 	    4400001	        81,008,600
    TC_CELL	    IX_TC_CELL_01	13	                RANGE	    12	        R 	    4800001	        40,683,687
    TC_CELL	    IDX_DW_UPDDTM	6	                RANGE	    5	        R 	    2000001	        53,549,174
    TC_CELL	    IDX_DW_UPDDTM	7	                RANGE	    6	        R 	    2400001	        50,482,596
    TC_CELL	    IDX_DW_UPDDTM	8	                RANGE	    7	        R 	    2800001	        54,368,994
    TC_CELL	    IDX_DW_UPDDTM	9	                RANGE	    8	        R 	    3200001	        55,547,316
    TC_CELL	    IDX_DW_UPDDTM	10	                RANGE	    9	        R 	    3600001	        77,420,538
    TC_CELL	    IDX_DW_UPDDTM	11	                RANGE	    10	        R 	    4000001	        80,402,102
    TC_CELL	    IDX_DW_UPDDTM	12	                RANGE	    11	        R 	    4400001	        81,008,600
    TC_CELL	    IDX_DW_UPDDTM	13	                RANGE	    12	        R 	    4800001	        40,683,687
    TC_CELL	    FK_CC_CT_1	    6	                RANGE	    5	        R 	    2000001	        53,549,174
    TC_CELL	    FK_CC_CT_1	    7	                RANGE	    6	        R 	    2400001	        50,482,596
    TC_CELL	    FK_CC_CT_1	    8	                RANGE	    7	        R 	    2800001	        54,368,994
    TC_CELL	    FK_CC_CT_1	    9	                RANGE	    8	        R 	    3200001	        55,547,316
    TC_CELL	    FK_CC_CT_1	    10	                RANGE	    9	        R 	    3600001	        77,420,538
    TC_CELL	    FK_CC_CT_1	    11	                RANGE	    10	        R 	    4000001	        80,402,102
    TC_CELL	    FK_CC_CT_1	    12	                RANGE	    11	        R 	    4400001	        81,008,600
    TC_CELL	    FK_CC_CT_1	    13	                RANGE	    12	        R 	    4800001	        40,683,687
*/

ALTER INDEX FK_CC_CT_1 on TC_CELL REBUILD PARTITION = 6 WITH (ONLINE=ON)    -- 00:00:53
GO
ALTER INDEX FK_CC_CT_1 on TC_CELL REBUILD PARTITION = 7 WITH (ONLINE=ON)
GO
ALTER INDEX FK_CC_CT_1 on TC_CELL REBUILD PARTITION = 8 WITH (ONLINE=ON)
GO
ALTER INDEX FK_CC_CT_1 on TC_CELL REBUILD PARTITION = 9 WITH (ONLINE=ON)
GO
ALTER INDEX FK_CC_CT_1 on TC_CELL REBUILD PARTITION = 10 WITH (ONLINE=ON)    -- 00:01:28
GO
ALTER INDEX FK_CC_CT_1 on TC_CELL REBUILD PARTITION = 11 WITH (ONLINE=ON)    -- 00:01:28
GO
ALTER INDEX FK_CC_CT_1 on TC_CELL REBUILD PARTITION = 12 WITH (ONLINE=ON)    -- 00:01:28
GO
ALTER INDEX FK_CC_CT_1 on TC_CELL REBUILD PARTITION = 13 WITH (ONLINE=ON)    -- 00:00:44
GO

ALTER INDEX IX_TC_CELL_01 on TC_CELL REBUILD PARTITION = 6 WITH (ONLINE=ON) -- 00:01:17
GO
ALTER INDEX IX_TC_CELL_01 on TC_CELL REBUILD PARTITION = 7 WITH (ONLINE=ON) -- 00:01:29
GO
ALTER INDEX IX_TC_CELL_01 on TC_CELL REBUILD PARTITION = 8 WITH (ONLINE=ON) -- 00:01:29
GO
ALTER INDEX IX_TC_CELL_01 on TC_CELL REBUILD PARTITION = 9 WITH (ONLINE=ON) -- 00:01:32
GO
ALTER INDEX IX_TC_CELL_01 on TC_CELL REBUILD PARTITION = 10 WITH (ONLINE=ON) -- 00:02:01
GO
ALTER INDEX IX_TC_CELL_01 on TC_CELL REBUILD PARTITION = 11 WITH (ONLINE=ON) -- 00:02:19
GO
ALTER INDEX IX_TC_CELL_01 on TC_CELL REBUILD PARTITION = 12 WITH (ONLINE=ON) -- 00:02:04
GO
ALTER INDEX IX_TC_CELL_01 on TC_CELL REBUILD PARTITION = 13 WITH (ONLINE=ON) -- 00:01:06
GO

ALTER INDEX PK_TC_CELL on TC_CELL REBUILD PARTITION = 6 WITH (ONLINE=ON)    -- 00:02:32
GO
ALTER INDEX PK_TC_CELL on TC_CELL REBUILD PARTITION = 7 WITH (ONLINE=ON, MAXDOP=4)    -- 00:02:27     --MAXDOP이 안 먹힘. 무조건 2로됨
GO
ALTER INDEX PK_TC_CELL on TC_CELL REBUILD PARTITION = 8 WITH (ONLINE=ON, SORT_IN_TEMPDB=ON) --00:03:11  더걸림
GO
ALTER INDEX PK_TC_CELL on TC_CELL REBUILD PARTITION = 9 WITH (ONLINE=ON)    -- 00:02:38
GO
ALTER INDEX PK_TC_CELL on TC_CELL REBUILD PARTITION = 10 WITH (ONLINE=ON)    -- 00:03:45
GO
ALTER INDEX PK_TC_CELL on TC_CELL REBUILD PARTITION = 11 WITH (ONLINE=ON)    -- 00:03:44
GO
ALTER INDEX PK_TC_CELL on TC_CELL REBUILD PARTITION = 12 WITH (ONLINE=ON)    -- 00:03:48
GO
ALTER INDEX PK_TC_CELL on TC_CELL REBUILD PARTITION = 13 WITH (ONLINE=ON)    -- 00:02:03
GO

파티션별로는 통계FULLSCAN이 자동으로 안됨

UPDATE STATISTICS TC_CELL FK_CC_CT_1 WITH FULLSCAN  -- 00:01:43
GO

UPDATE STATISTICS TC_CELL IX_TC_CELL_01 WITH FULLSCAN  -- 00:03:13
GO

UPDATE STATISTICS TC_CELL PK_TC_CELL WITH FULLSCAN  -- 00:01:41
GO


-- 04. TC_CELL_PROCESS
/*
    name             rows         reserved          data                index_size          unused
    ---------------  -----------  -------------     -------------       -------------       ------------------
    TC_CELL_PROCESS  10204339082  7,019,037,944 KB  3,850,566,840 KB    3,165,429,752 KB    3,041,352 KB

    SchemaName  TBL_CreateDate           TableName        IndexType     IndexName              IndexSizeKB  IndexColumn                             IncludeColumn  STATISTICUPDATEDATE      IS_UNIQUE  IS_UNIQUE_CONSTRAINT  IS_PRIMARY_KEY  HAS_FILTER  FILTER_DEFINITION  IS_DISABLED  database_id  object_id   index_id  user_seeks  user_scans  user_lookups  user_updates  last_user_seek           last_user_scan           last_user_lookup         last_user_update  system_seeks  system_scans  system_lookups  system_updates  last_system_seek  last_system_scan         last_system_lookup  last_system_update  database_id  object_id   index_id  partition_number  leaf_insert_count  leaf_delete_count  leaf_update_count  leaf_ghost_count  nonleaf_insert_count  nonleaf_delete_count  nonleaf_update_count  leaf_allocation_count  nonleaf_allocation_count  leaf_page_merge_count  nonleaf_page_merge_count  range_scan_count  singleton_lookup_count  forwarded_fetch_count  lob_fetch_in_pages  lob_fetch_in_bytes  lob_orphan_create_count  lob_orphan_insert_count  row_overflow_fetch_in_pages  row_overflow_fetch_in_bytes  column_value_push_off_row_count  column_value_pull_in_row_count  row_lock_count  row_lock_wait_count  row_lock_wait_in_ms  page_lock_count  page_lock_wait_count  page_lock_wait_in_ms  index_lock_promotion_attempt_count  index_lock_promotion_count  page_latch_wait_count  page_latch_wait_in_ms  page_io_latch_wait_count  page_io_latch_wait_in_ms  tree_page_latch_wait_count  tree_page_latch_wait_in_ms  tree_page_io_latch_wait_count  tree_page_io_latch_wait_in_ms  page_compression_attempt_count  page_compression_success_count
    ----------  -----------------------  ---------------  ------------  ---------------------  -----------  --------------------------------------  -------------  -----------------------  ---------  --------------------  --------------  ----------  -----------------  -----------  -----------  ----------  --------  ----------  ----------  ------------  ------------  -----------------------  -----------------------  -----------------------  ----------------  ------------  ------------  --------------  --------------  ----------------  -----------------------  ------------------  ------------------  -----------  ----------  --------  ----------------  -----------------  -----------------  -----------------  ----------------  --------------------  --------------------  --------------------  ---------------------  ------------------------  ---------------------  ------------------------  ----------------  ----------------------  ---------------------  ------------------  ------------------  -----------------------  -----------------------  ---------------------------  ---------------------------  -------------------------------  ------------------------------  --------------  -------------------  -------------------  ---------------  --------------------  --------------------  ----------------------------------  --------------------------  ---------------------  ---------------------  ------------------------  ------------------------  --------------------------  --------------------------  -----------------------------  -----------------------------  ------------------------------  ------------------------------
    dbo         2018-06-12 14:41:36.670  TC_CELL_PROCESS  CLUSTERED     PK_TC_CELL_PROCESS     3,917,215,448   CELL_ID ASC, OP_ID ASC, INS_TIME ASC    NULL           2021-05-31 09:00:19.490  1          0                     1               0           NULL               0            6            1449108253  1         163         5           28            0             2021-05-26 20:32:49.067  2021-05-17 15:22:16.673  2021-03-30 14:44:08.600  NULL              0             75            0               0               NULL              2021-05-26 14:12:23.030  NULL                NULL                6            1449108253  1         1                 0                  0                  0                  0                 0                     0                     0                     0                      0                         0                      0                         33593             0                       0                      0                   0                   0                        0                        0                            0                            0                                0                               0               0                    0                    0                0                     0                     0                                   0                           0                      0                      22                        8                         0                           0                           11                             6                              0                               0
  --dbo         2018-06-12 14:41:36.670  TC_CELL_PROCESS  NONCLUSTERED  IDX_DW_UPDDTM          1,432,466,704   UPDDTTM ASC, INS_TIME ASC               NULL           2021-05-31 09:01:52.857  0          0                     0               0           NULL               0            6            1449108253  3         29          1           0             0             2021-05-26 14:13:00.177  2021-04-07 11:25:03.970  NULL                     NULL              0             40            0               0               NULL              2021-05-26 14:12:00.850  NULL                NULL                6            1449108253  3         1                 0                  0                  0                  0                 0                     0                     0                     0                      0                         0                      0                         1                 0                       0                      0                   0                   0                        0                        0                            0                            0                                0                               0               0                    0                    0                0                     0                     0                                   0                           0                      0                      2                         1                         0                           0                           2                              1                              0                               0
    dbo         2018-06-12 14:41:36.670  TC_CELL_PROCESS  NONCLUSTERED  IX_TC_CELL_PROCESS_N1  1,666,350,768   TRAY_NO ASC, CELL_ID ASC, INS_TIME ASC  NULL           2021-05-31 09:01:12.463  0          0                     0               0           NULL               0            6            1449108253  2         62          7           0             0             2021-04-07 11:29:16.527  2020-12-28 08:21:30.593  NULL                     NULL              0             34            0               0               NULL              2021-03-04 11:33:13.970  NULL                NULL                6            1449108253  2         1                 0                  0                  0                  0                 0                     0                     0                     0                      0                         0                      0                         8574              0                       0                      0                   0                   0                        0                        0                            0                            0                                0                               0               0                    0                    0                0                     0                     0                                   0                           0                      0                      22                        112                       0                           0                           22                             112                            0                               0

*/


ALTER INDEX IX_TC_CELL_PROCESS_N1 on TC_CELL_PROCESS REBUILD PARTITION = 37
GO
ALTER INDEX IX_TC_CELL_PROCESS_N1 on TC_CELL_PROCESS REBUILD PARTITION = 38
GO
ALTER INDEX IX_TC_CELL_PROCESS_N1 on TC_CELL_PROCESS REBUILD PARTITION = 39
GO
ALTER INDEX IX_TC_CELL_PROCESS_N1 on TC_CELL_PROCESS REBUILD PARTITION = 40
GO
ALTER INDEX IX_TC_CELL_PROCESS_N1 on TC_CELL_PROCESS REBUILD PARTITION = 41
GO
ALTER INDEX IX_TC_CELL_PROCESS_N1 on TC_CELL_PROCESS REBUILD PARTITION = 42 WITH (ONLINE=ON)    -- 01:12:03     2033439149건
GO

SET STATISTICS PROFILE ON

ALTER INDEX IX_TC_CELL_PROCESS_N1 on TC_CELL_PROCESS REBUILD PARTITION = 43 WITH (ONLINE=ON)    -- 00:00:21     9911231건
GO



ALTER INDEX PK_TC_CELL_PROCESS on TC_CELL_PROCESS REBUILD PARTITION = 37
GO
ALTER INDEX PK_TC_CELL_PROCESS on TC_CELL_PROCESS REBUILD PARTITION = 38
GO
ALTER INDEX PK_TC_CELL_PROCESS on TC_CELL_PROCESS REBUILD PARTITION = 39
GO
ALTER INDEX PK_TC_CELL_PROCESS on TC_CELL_PROCESS REBUILD PARTITION = 40
GO
ALTER INDEX PK_TC_CELL_PROCESS on TC_CELL_PROCESS REBUILD PARTITION = 41
GO
ALTER INDEX PK_TC_CELL_PROCESS on TC_CELL_PROCESS REBUILD PARTITION = 42 WITH (ONLINE=ON, SORT_IN_TEMPDB=ON, MAXDOP=4)  -- 02:45:20          2033439149건(20억건)
GO

ALTER INDEX PK_TC_CELL_PROCESS on TC_CELL_PROCESS REBUILD PARTITION = 43 WITH (ONLINE=ON, SORT_IN_TEMPDB=ON)  -- 00:00:41          9911231건
GO

--ALTER INDEX PK_TC_CELL_PROCESS on TC_CELL_PROCESS REBUILD PARTITION = 43 WITH (ONLINE=ON, SORT_IN_TEMPDB=ON, MAXDOP=4)  -- 00:00:41          9911231건
--GO

--ALTER INDEX PK_TC_CELL_PROCESS on TC_CELL_PROCESS REBUILD PARTITION = 43 WITH (ONLINE=ON, SORT_IN_TEMPDB=ON, MAXDOP=8)  -- 00:00:52          9911231건
--GO




--UPDATE STATISTICS TC_CELL_PROCESS IX_TC_CELL_PROCESS_N1 WITH FULLSCAN  -- 1시간 30 넘어도 안됨. cpu100% 침
UPDATE STATISTICS TC_CELL_PROCESS IX_TC_CELL_PROCESS_N1  -- 00:00:38
GO

UPDATE STATISTICS TC_CELL_PROCESS PK_TC_CELL_PROCESS -- 00:00:22
GO